name: CI Pipeline

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Login to github container registry
        env:
          CR_PAT: ${{secrets.GITHUB_TOKEN}}
        run: echo $CR_PAT | docker login ghcr.io -u MixR-gg --password-stdin
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/mixr-gg/stripe-sync-engine
      - name: Push to Container Registry
        run: docker push ghcr.io/mixr-gg/stripe-sync-engine:latest
